name: Build and deploy on push

on: 
  push:
    branches: 
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with Maven
      uses: LucaFeger/action-maven-cli@765e218a50f02a12a7596dc9e7321fc385888a27
      with:
        args: clean install
    - name: Build Docker Image
      run: docker build -t docker.pkg.github.com/biospheere/promcord/promcord . 
    - name: Push the image to GPR
      run: |
        docker login docker.pkg.github.com -u publisher -p "${DOCKER_PASSWORD}"
        docker push docker.pkg.github.com/biospheere/promcord/promcord
      env: 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
      